name = "Kelvin"
print("Customer: ", name)
print()
print()
coffee = float(input("Coffee: $"))
cake = float(input("Cake: $"))
print()
print()
print("Total Cost: $", coffee + cake)
print()
print()
print("Thank you for visiting!")